// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-jaxoGpQScsUCdVvieBq1gUw2dT30qF8',
    appId: '1:272730484218:web:5c8f7dd53ea51a75d28843',
    messagingSenderId: '272730484218',
    projectId: 'tweetguess-prod-ef19d',
    authDomain: 'tweetguess-prod-ef19d.firebaseapp.com',
    storageBucket: 'tweetguess-prod-ef19d.appspot.com',
    measurementId: 'G-M5GJQ0H10T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxlnmB5jiLCHnl7MQlRiCJy-b1B53bPV0',
    appId: '1:272730484218:android:a7bb36c1671fce9dd28843',
    messagingSenderId: '272730484218',
    projectId: 'tweetguess-prod-ef19d',
    storageBucket: 'tweetguess-prod-ef19d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrpSdpoJSzp3vPsYu1eYj4H2XxtliALIM',
    appId: '1:272730484218:ios:e916a7f4a83f1a6bd28843',
    messagingSenderId: '272730484218',
    projectId: 'tweetguess-prod-ef19d',
    storageBucket: 'tweetguess-prod-ef19d.appspot.com',
    iosBundleId: 'eu.tweetguess.tweetguess',
  );
}
